# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/items.proto for package 'itemsproto'

require 'grpc'
require 'proto/items'

module Itemsproto
  module Items
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'itemsproto.Items'

      rpc :All, Empty, AllResponse
      rpc :Create, CreateRequest, Empty
      rpc :Get, GetRequest, Item
      rpc :Update, UpdateRequest, Item
      rpc :Delete, DeleteRequest, Empty
    end

    Stub = Service.rpc_stub_class
  end
end
